branches:
  only:
    - master
sudo: required
language: generic
services:
  - docker
env:
  - PROJECTS="$(readlink -f ..)"
before_script:
  - cat ~/.gitconfig && rm ~/.gitconfig
script:
  - ./deploy.sh
#  - mv deploy.*.sh deploy.sh  # https://github.com/dmtucker/config/issues/36
  - docker build .
